// Native projects are generated by Expo; preserve the icon resources on every prebuild.
const { withDangerousMod } = require('expo/config-plugins');
const { cpSync, readdirSync, rmSync } = require('node:fs');
const { join } = require('node:path');
module.exports = function icons(config) {
  config = withDangerousMod(config, ['android', async (c) => {
    const resources = join(c.modRequest.platformProjectRoot, 'app/src/main/res');
    // Expo emits WebP legacy icons. Android treats PNG/WebP with the same stem as duplicates.
    for (const folder of readdirSync(resources).filter((name) => name.startsWith('mipmap-'))) {
      for (const file of ['ic_launcher.webp', 'ic_launcher_round.webp']) {
        rmSync(join(resources, folder, file), { force: true });
      }
    }
    cpSync(join(c.modRequest.projectRoot, 'assets/android'), resources, { recursive: true });
    return c;
  }]);
  return withDangerousMod(config, ['ios', async (c) => {
    cpSync(join(c.modRequest.projectRoot, 'assets/AppIcon.appiconset'), join(c.modRequest.platformProjectRoot, c.modRequest.projectName, 'Images.xcassets/AppIcon.appiconset'), { recursive: true });
    return c;
  }]);
};
